import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import Lottie from "react-lottie";
import PassingCardsAnimation from "../lotties/passing-cards.json";
import ArrowRightAnimation from "../lotties/arrow-right.json";
import { useRouter } from "next/router";
import { useState } from "react";

interface IHomeProps {
    totalValue: number;
}

const ButtonPurchase = styled.button`
    padding: 15px 30px;
    max-width: 200px;

    font-family: "Roboto", sans-serif;
    font-weight: 700;
    box-shadow: 2px 5px 1px #750606;
    transition: 1s;
    margin: 0 0 7vh 0;
    border-radius: 5px;
    background-color: #d62e2e;
    color: white;
    border: none;

    &:hover {
        margin: 1vh 0 6vh 0;
        transition: 1s;
        cursor: pointer;
        box-shadow: 0px 0px 0px #931111;
    }
`;

const Main = styled.main`
    display: flex;
    flex-direction: column;
    max-width: 400px;
    justify-content: space-between;
    align-items: center;
`;

const Body = styled.div`
    display: flex;
    justify-content: center;
    align-items: center;
    height: 80vh;
`;

const TotalSales = styled.span`
    font-size: 2rem;
    color: #258a25;
`;

const Home: NextPage<IHomeProps> = ({ totalValue }) => {
    const router = useRouter();

    const [clickedNextPage, setClickedNextPage] = useState(false);

    const goToCart = () => {
        setClickedNextPage(true);
        setTimeout(() => router.push("/checkout"), 2000);
    }

    return (
        <Body>
            <Head>
                <title>Loja do Paulo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {clickedNextPage 
                ? <Lottie options={{ loop: false, autoplay: true, animationData: ArrowRightAnimation }} height={1000} width={1000} />
                : (
                    <Main>
                        <Lottie options={{ loop: true, autoplay: true, animationData: PassingCardsAnimation }}  height={300} width={300} />
                        <ButtonPurchase onClick={goToCart}>Fazer uma venda</ButtonPurchase>
                        <h2>
                            Total de vendas: <TotalSales>{totalValue.toLocaleString("pt-BR", {style: "currency",currency: "BRL"})}</TotalSales>
                        </h2>
                    </Main>
                )
            }
        </Body>
    );
};

export async function getStaticProps() {
    const response = await fetch(`${process.env.API_URL}/total-value`);
    const data = await response.json();

    return {
        props: { ...data },
    };
}

export default Home;
